### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by KshitijKarnawat** [KshitijKarnawat/a-star-path-planner#5]
### Steps to recreate issue:

Enter x coordinate of start point: 10
Enter y coordinate of start point: 10
Enter the start angle of the robot in multiples of 30deg(0 <= theta <= 360): 0
Enter x coordinate of goal point: 10
Enter y coordinate of goal point: 100
Enter the start angle of the robot in multiples of 30deg(0 <= theta <= 360): 0
Enter the step length of the robot (1 <= L <= 10): 1

### Terminal Output:

Traceback (most recent call last):
  File "a_star_kshitij_abhishek.py", line 420, in <module>
    main()
  File "a_star_kshitij_abhishek.py", line 405, in main
    explored_nodes, shortest_path = astar(L, start_point, goal_point)
  File "a_star_kshitij_abhishek.py", line 318, in astar
    if child_cost + cost_to_come < open_list_info[child.coord].cost_to_come:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by armgits** [comment]
This was happening because the cost to go function `calc_manhattan_distance` was returning an array instead of a number. Updated the cost to go heuristic and fixed it.
